### ISSUE TITLE
view.Data Start and End are always set to time.Now()

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#485] opened 2018-02-23 21:15 UTC
This is seems wrong. I'm more worried that it might mean we aren't correctly exporting to Stackdriver ( the only reader of Start and End data).

**Comment by rakyll** [comment] 2018-02-26 23:44
Duplicate of https://github.com/census-instrumentation/opencensus-go/issues/200.

**Closed by rakyll** 2018-02-26 23:44 UTC
Labels: bug, stats
