### ISSUE TITLE
plugin/ochttp: implement io.ReadFrom

### ISSUE THREAD

**Issue by groob** [census-instrumentation/opencensus-go#744] opened 2018-05-07 14:40 UTC
https://github.com/census-instrumentation/opencensus-go/issues/642 was opened to implement the hijacker interface for websocket support. 
Beside Hijacker and Flusher the default implementation of `http.ResponseWriter` supports a few other additional "upgradable" interfaces. When these are not implemented in middleware it can lead to subtle bugs and performance regressions in proxies that use the http plugin. 

https://avtok.com/2014/11/05/interface-upgrades.html
https://github.com/felixge/httpsnoop#why-this-package-exists

Popular middleware packages like https://github.com/gorilla/handlers and [chi](https://github.com/go-chi/chi) implement the entire subset of these methods. It looks like the ochttp plugin only supports Hijack and Flush today, leaving `CloseNotify`, `Push`, and `ReadFrom`.

**Comment by odeke-em** [comment] 2018-05-07 20:07
Thank you for raising this @groob!

I actually also just encountered this while instrumenting a popular webserver
```shell
rec: httpserver.NonCloseNotifierError{Underlying:(*ochttp.trackingResponseWriter)(0xc0001dc070)
```

**Comment by odeke-em** [comment] 2018-05-10 07:08
@groob I've mailed this PR https://github.com/census-instrumentation/opencensus-go/pull/747 PTAL. I also need most of the interfaces implemented to complete the integration that I am working on.

**Comment by odeke-em** [comment] 2018-05-13 23:41
Alright, I've merged the PR that implements the pure HTTP interfaces:
* `http.Pusher`
* `http.CloseNotifier`

only `io.ReadFrom` is left

**Comment by basvanbeek** [comment] 2018-05-14 07:59
I'm not convinced the current approach is a good one. The implementation done in #747 has the negative side effect of implementing all "upgradable" interfaces that might not have been implemented by the underlying wrapped implementation. If any code is making choices based on an upgradable interface being implemented or not it will potentially get a false positive from ochttp.

The `httpsnoop` package as found at https://github.com/felixge/httpsnoop actually correctly deals with this by returning a handler that only returns an implementation which includes the actually wrapped interfaces and not all of them. Since this interface logic from httpsnoop is decoupled from its own metrics middleware handling we could use httpsnoop as a dependency and save ourselves some work.

**Comment by basvanbeek** [comment] 2018-05-15 12:13
If we don't like taking an additional dependency that's fine, we can roll our own. I do have a strong negative sentiment against the false positive scenario as we should not be introducing hidden quirks that change expected behavior when ochttp is put in between. The solution as presented by httpsnoop is not a difficult one to build, has minimal overhead and makes our middleware properly transparent.

**Closed** 2018-07-20 19:22 UTC
Labels: http, next, up-for-grabs
