### ISSUE TITLE
stats: AggregationData and Aggregation should match for ViewData

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-go#158] opened 2017-11-27 19:11 UTC
For example, if a `View` has `Sum` aggregation, and a `ViewData` is created from this `View`, then all `AggregationData` associated with this `ViewData` should be `SumData`.

**Comment by rakyll** [comment] 2017-11-27 19:24
This is already what's happening but we don't have generics or union types in Go. It is not possible for the types to express this. Do you have any suggestions what the APIs should look like?

**Comment by songy23** [comment] 2017-11-27 19:44
I see, just noted in Go Rows are generated from Collectors. If users could create Rows manually, I think it's useful to validate the types of `Row.AggregationData` and `View.Collector.Aggregation` when creating ViewData, to prevent issues like https://github.com/census-instrumentation/opencensus-go/issues/146.

**Comment by rakyll** [comment] 2018-01-08 18:29
If users create Rows manually, it is not on the path of the collector. They may still end up having inconsistent rows. We can provide a constructor for the Row but I think it is on overkill for a type not going to be used by the end user often.

Closing this given we don't have many options here.

(Note that #146 is caused by the inconsistency between remote measure descriptor and the local measure, not the inconsistency between aggregation type and the view data.)

**Closed by rakyll** 2018-01-08 18:29 UTC
Labels: api, enhancement, stats
