### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#455] opened 2018-02-16 07:02 UTC
This issue is a placeholder to solve the outstanding Q1 issue that I am tasked with: benchmarking

The initial direction was to make a gRPC client and a gRPC server, instrument them with various configurations and permutations of OpenCensus and at various QPS.

Because instrumenting both sides(client and server) requires different permutations of NoStats, NoTrace
{NoStats, NoTrace} = 4 cases
Client{NoStats, NoTrace} <--> Server{NoStats, NoTrace} = 4 x 4 = 16 cases
QPS values{1, 10, 100, 1000} * (Client{NoStats, NoTrace} <--> Server{NoStats, NoTrace}) = 4 * 16 = 64 cases

**Comment by odeke-em** [comment] 2018-02-16 07:03
Code at https://github.com/census-instrumentation/opencensus-go/pull/450

**Comment by odeke-em** [comment] 2018-02-16 07:06
Results look like this 
```shell
BenchmarkPlainClientPlainServer1QPS-4                            	   10000	    163612 ns/op	    7863 B/op	     149 allocs/op
BenchmarkPlainClientPlainServer10QPS-4                           	    3000	    537491 ns/op	   74988 B/op	    1323 allocs/op
BenchmarkPlainClientPlainServer100QPS-4                          	     500	   3268128 ns/op	  747795 B/op	   12929 allocs/op
BenchmarkPlainClientPlainServer1000QPS-4                         	      50	  34048604 ns/op	 7645554 B/op	  129358 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceNoStatsServer1QPS-4          	   10000	    181696 ns/op	    8852 B/op	     165 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceNoStatsServer10QPS-4         	    3000	    527740 ns/op	   84929 B/op	    1482 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceNoStatsServer100QPS-4        	     500	   3614156 ns/op	  847895 B/op	   14544 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceNoStatsServer1000QPS-4       	      30	  36274426 ns/op	 8700109 B/op	  146066 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceYesStatsServer1QPS-4         	   10000	    198839 ns/op	   10187 B/op	     198 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceYesStatsServer10QPS-4        	    3000	    575029 ns/op	   98386 B/op	    1824 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceYesStatsServer100QPS-4       	     300	   4546124 ns/op	  981024 B/op	   17970 allocs/op
BenchmarkNoTraceNoStatsClientNoTraceYesStatsServer1000QPS-4      	      30	  47809234 ns/op	10095203 B/op	  182436 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceNoStatsServer1QPS-4         	   10000	    182362 ns/op	    9091 B/op	     172 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceNoStatsServer10QPS-4        	    3000	    532748 ns/op	   87308 B/op	    1553 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceNoStatsServer100QPS-4       	     500	   3741976 ns/op	  871581 B/op	   15240 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceNoStatsServer1000QPS-4      	      30	  36395280 ns/op	 8995387 B/op	  153804 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceYesStatsServer1QPS-4        	   10000	    190561 ns/op	   10421 B/op	     205 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceYesStatsServer10QPS-4       	    3000	    596360 ns/op	  100735 B/op	    1893 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceYesStatsServer100QPS-4      	     300	   4668629 ns/op	 1006063 B/op	   18689 allocs/op
BenchmarkNoTraceNoStatsClientYesTraceYesStatsServer1000QPS-4     	      30	  50047677 ns/op	10337041 B/op	  189444 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceNoStatsServer1QPS-4         	   10000	    193963 ns/op	   10187 B/op	     198 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceNoStatsServer10QPS-4        	    3000	    601365 ns/op	   98387 B/op	    1823 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceNoStatsServer100QPS-4       	     300	   4444063 ns/op	  981014 B/op	   17967 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceNoStatsServer1000QPS-4      	      30	  47928681 ns/op	10104513 B/op	  182452 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceYesStatsServer1QPS-4        	   10000	    209847 ns/op	   12422 B/op	     246 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceYesStatsServer10QPS-4       	    2000	    629139 ns/op	  120693 B/op	    2307 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceYesStatsServer100QPS-4      	     300	   5168239 ns/op	 1205599 B/op	   22778 allocs/op
BenchmarkNoTraceYesStatsClientNoTraceYesStatsServer1000QPS-4     	      20	  57227189 ns/op	12347009 B/op	  230789 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceNoStatsServer1QPS-4        	   10000	    196511 ns/op	   11577 B/op	     220 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceNoStatsServer10QPS-4       	    2000	    687993 ns/op	  112263 B/op	    2046 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceNoStatsServer100QPS-4      	     300	   4904748 ns/op	 1119885 B/op	   20202 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceNoStatsServer1000QPS-4     	      20	  53287280 ns/op	11505105 B/op	  204843 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceYesStatsServer1QPS-4       	   10000	    209829 ns/op	   12657 B/op	     253 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceYesStatsServer10QPS-4      	    2000	    625365 ns/op	  123017 B/op	    2377 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceYesStatsServer100QPS-4     	     300	   5694859 ns/op	 1229013 B/op	   23473 allocs/op
BenchmarkNoTraceYesStatsClientYesTraceYesStatsServer1000QPS-4    	      20	  57791112 ns/op	12573064 B/op	  237864 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceNoStatsServer1QPS-4         	   10000	    180132 ns/op	   10233 B/op	     187 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceNoStatsServer10QPS-4        	    2000	    554425 ns/op	   98852 B/op	    1704 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceNoStatsServer100QPS-4       	     300	   3953507 ns/op	  989044 B/op	   16820 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceNoStatsServer1000QPS-4      	      30	  41172264 ns/op	10085614 B/op	  168487 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceYesStatsServer1QPS-4        	   10000	    198043 ns/op	   11578 B/op	     220 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceYesStatsServer10QPS-4       	    2000	    669057 ns/op	  112251 B/op	    2045 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceYesStatsServer100QPS-4      	     300	   5584159 ns/op	 1121367 B/op	   20200 allocs/op
BenchmarkYesTraceNoStatsClientNoTraceYesStatsServer1000QPS-4     	      20	  53170285 ns/op	11503365 B/op	  204717 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceNoStatsServer1QPS-4        	   10000	    198351 ns/op	   10475 B/op	     194 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceNoStatsServer10QPS-4       	    2000	    582609 ns/op	  101205 B/op	    1775 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceNoStatsServer100QPS-4      	     300	   4056443 ns/op	 1012924 B/op	   17524 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceNoStatsServer1000QPS-4     	      30	  43242979 ns/op	10340377 B/op	  175775 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceYesStatsServer1QPS-4       	   10000	    210603 ns/op	   11808 B/op	     227 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceYesStatsServer10QPS-4      	    2000	    701702 ns/op	  114599 B/op	    2115 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceYesStatsServer100QPS-4     	     300	   5281952 ns/op	 1143747 B/op	   20904 allocs/op
BenchmarkYesTraceNoStatsClientYesTraceYesStatsServer1000QPS-4    	      20	  55431835 ns/op	11741519 B/op	  211890 allocs/op
BenchmarkYesTraceYesStatsClientYesTraceYesStatsServer1QPS-4      	    5000	    219655 ns/op	   14121 B/op	     275 allocs/op
BenchmarkYesTraceYesStatsClientYesTraceYesStatsServer10QPS-4     	    2000	    729268 ns/op	  137567 B/op	    2599 allocs/op
BenchmarkYesTraceYesStatsClientYesTraceYesStatsServer100QPS-4    	     200	   6032821 ns/op	 1374857 B/op	   25716 allocs/op
BenchmarkYesTraceYesStatsClientYesTraceYesStatsServer1000QPS-4   	      20	  63603007 ns/op	14029447 B/op	  260170 allocs/op
```
However, I wonder how we are going to consume these results.

@rakyll liased with the gRPC team and they recommended that she add a flag to their current benchmarks that are run daily.

Next step is for us to have microbenchmarks e.g calls that are untraced and those that aren't, they don't have to be across gRPC backends. They could just be across plain HTTP/RPC boundaries and the goal would be to measure the added expenses between tracing and not tracing, plus also metric collection.

**Comment by rakyll** [comment] 2018-03-06 23:55
Duplicate of https://github.com/census-instrumentation/opencensus-go/issues/111.

**Closed by rakyll** 2018-03-06 23:55 UTC
Labels: in progress
