### ISSUE TITLE
exporter/stats/stackdriver: race with adding new data

### ISSUE THREAD

**Issue by jcd2** [census-instrumentation/opencensus-go#223] opened 2017-12-04 15:46 UTC
Exported ViewData are bundled to be uploaded later, so when the aggregated distribution data is eventually read it may also be getting written to.  Exporter.Export should make a copy of the data before returning, or the stats worker should be exporting read-only copies.

**Comment by odeke-em** [comment] 2017-12-04 23:11
I think implementing a copy in the worker would make the API simple and nicer but even better guarantee to all and future exporters that the data that they are dealing with is concurrency safe.

**Comment by odeke-em** [comment] 2017-12-04 23:23
Alas, great hunch @jcd2 here is a test that reproduces the data race
```diff
diff --git a/exporter/stats/stackdriver/stackdriver_test.go b/exporter/stats/stackdriver/stackdriver_test.go
index ae58ffa..7fb246d 100644
--- a/exporter/stats/stackdriver/stackdriver_test.go
+++ b/exporter/stats/stackdriver/stackdriver_test.go
@@ -19,7 +19,9 @@ import (
 	"testing"
 	"time"
 
+	"google.golang.org/api/option"
 	"google.golang.org/genproto/googleapis/api/label"
+	"google.golang.org/grpc"
 
 	"go.opencensus.io/stats"
 	"go.opencensus.io/tag"
@@ -508,3 +510,68 @@ func newTestDistViewData(v *stats.View, start, end time.Time) *stats.ViewData {
 		End:   end,
 	}
 }
+
+func TestBundlerRace(t *testing.T) {
+	exporter, err := NewExporter(Options{
+		ClientOptions: []option.ClientOption{
+			option.WithGRPCConn(&grpc.ClientConn{}),
+		},
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	m, err := stats.NewMeasureFloat64("test-measure", "measure desc", "unit")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer stats.DeleteMeasure(m)
+
+	v, err := stats.NewView("distview", "desc", nil, m, stats.DistributionAggregation([]float64{2, 4, 7}), stats.Interval{})
+	if err != nil {
+		t.Fatal(err)
+	}
+	if err := stats.RegisterView(v); err != nil {
+		t.Fatal(err)
+	}
+	defer v.Unregister()
+
+	vd := &stats.ViewData{
+		View: v,
+		Rows: []*stats.Row{
+			{Data: &stats.DistributionData{
+				Count:           5,
+				Min:             1,
+				Max:             7,
+				Mean:            3,
+				SumOfSquaredDev: 1.5,
+				CountPerBucket:  []int64{2, 2, 1},
+			}},
+		},
+	}
+
+	doneCh := make(chan bool, 1)
+
+	// 1. Producer goroutine
+	go func() {
+		for {
+			select {
+			case <-doneCh:
+				return
+			case <-time.After(10 * time.Millisecond):
+
+				v, _ := stats.NewView("distview", "desc", nil, m, stats.DistributionAggregation([]float64{2, 4, 7}), stats.Interval{})
+				vd.View = v
+				vd.End = time.Now()
+				vd.Start = vd.End.Add(-1 * time.Hour)
+			}
+		}
+	}()
+
+	for i := 0; i < 24; i++ {
+		exporter.Export(vd)
+		<-time.After(15 * time.Millisecond)
+		exporter.Flush()
+	}
+	close(doneCh)
+}
```
giving 
```shell
$ go test -v -run=Race -race
=== RUN   TestBundlerRace
==================
WARNING: DATA RACE
Write at 0x00c4200c24b0 by goroutine 9:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:565 +0x276

Previous read at 0x00c4200c24b0 by goroutine 12:
  go.opencensus.io/exporter/stats/stackdriver.(*Exporter).upload()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:145 +0xbd
  go.opencensus.io/exporter/stats/stackdriver.NewExporter.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:107 +0x7a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:256 +0x106

Goroutine 9 (running) created at:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:557 +0xad5
  testing.tRunner()
      /Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:774 +0x16d

Goroutine 12 (finished) created at:
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:245 +0x2a2
  google.golang.org/api/support/bundler.(*Bundler).Flush()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:220 +0x55
  google.golang.org/api/support/bundler.(*Bundler).Flush-fm()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:173 +0x41
==================
==================
WARNING: DATA RACE
Read at 0x00c42019a3e8 by goroutine 14:
  go.opencensus.io/exporter/stats/stackdriver.(*Exporter).upload()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:110 +0xd7
  go.opencensus.io/exporter/stats/stackdriver.NewExporter.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:107 +0x7a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:256 +0x106

Previous write at 0x00c42019a3e8 by goroutine 9:
  go.opencensus.io/stats.NewView()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:70 +0x93
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:564 +0x258

Goroutine 14 (running) created at:
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:245 +0x2a2
  google.golang.org/api/support/bundler.(*Bundler).Flush()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:220 +0x55
  google.golang.org/api/support/bundler.(*Bundler).Flush-fm()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:173 +0x41

Goroutine 9 (running) created at:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:557 +0xad5
  testing.tRunner()
      /Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:774 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c4201bc168 by goroutine 14:
  go.opencensus.io/exporter/stats/stackdriver.(*Exporter).upload()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:110 +0xed
  go.opencensus.io/exporter/stats/stackdriver.NewExporter.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:107 +0x7a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:256 +0x106

Previous write at 0x00c4201bc168 by goroutine 9:
  go.opencensus.io/stats.NewView()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:70 +0x23b
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:564 +0x258

Goroutine 14 (running) created at:
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:245 +0x2a2
  google.golang.org/api/support/bundler.(*Bundler).Flush()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:220 +0x55
  google.golang.org/api/support/bundler.(*Bundler).Flush-fm()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:173 +0x41

Goroutine 9 (running) created at:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:557 +0xad5
  testing.tRunner()
      /Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:774 +0x16d
==================
--- FAIL: TestBundlerRace (0.42s)
	testing.go:727: race detected during execution of test
FAIL
exit status 1
FAIL	go.opencensus.io/exporter/stats/stackdriver	0.439s
Emmanuels-MacBook-Pro-2:stackdriver emmanuelodeke$ 
Emmanuels-MacBook-Pro-2:stackdriver emmanuelodeke$ go test -v -run=Race -race
=== RUN   TestBundlerRace
==================
WARNING: DATA RACE
Write at 0x00c4200a24b0 by goroutine 9:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:564 +0x276

Previous read at 0x00c4200a24b0 by goroutine 12:
  go.opencensus.io/exporter/stats/stackdriver.(*Exporter).upload()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:145 +0xbd
  go.opencensus.io/exporter/stats/stackdriver.NewExporter.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:107 +0x7a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:256 +0x106

Goroutine 9 (running) created at:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:556 +0xad5
  testing.tRunner()
      /Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:774 +0x16d

Goroutine 12 (finished) created at:
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:245 +0x2a2
  google.golang.org/api/support/bundler.(*Bundler).Flush()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:220 +0x55
  google.golang.org/api/support/bundler.(*Bundler).Flush-fm()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:173 +0x41
==================
==================
WARNING: DATA RACE
Read at 0x00c4201ac148 by goroutine 18:
  go.opencensus.io/exporter/stats/stackdriver.(*Exporter).upload()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:110 +0xd7
  go.opencensus.io/exporter/stats/stackdriver.NewExporter.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:107 +0x7a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:256 +0x106

Previous write at 0x00c4201ac148 by goroutine 9:
  go.opencensus.io/stats.NewView()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:70 +0x93
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:563 +0x258

Goroutine 18 (running) created at:
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:245 +0x2a2
  google.golang.org/api/support/bundler.(*Bundler).Flush()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:220 +0x55
  google.golang.org/api/support/bundler.(*Bundler).Flush-fm()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:173 +0x41

Goroutine 9 (running) created at:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:556 +0xad5
  testing.tRunner()
      /Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:774 +0x16d
==================
==================
WARNING: DATA RACE
Read at 0x00c4201aa108 by goroutine 18:
  go.opencensus.io/exporter/stats/stackdriver.(*Exporter).upload()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:110 +0xed
  go.opencensus.io/exporter/stats/stackdriver.NewExporter.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver.go:107 +0x7a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:256 +0x106

Previous write at 0x00c4201aa108 by goroutine 9:
  go.opencensus.io/stats.NewView()
      /Users/emmanuelodeke/go/src/go.opencensus.io/stats/view.go:70 +0x23b
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace.func1()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:563 +0x258

Goroutine 18 (running) created at:
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:245 +0x2a2
  google.golang.org/api/support/bundler.(*Bundler).Flush()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:220 +0x55
  google.golang.org/api/support/bundler.(*Bundler).Flush-fm()
      /Users/emmanuelodeke/go/src/google.golang.org/api/support/bundler/bundler.go:173 +0x41

Goroutine 9 (running) created at:
  go.opencensus.io/exporter/stats/stackdriver.TestBundlerRace()
      /Users/emmanuelodeke/go/src/go.opencensus.io/exporter/stats/stackdriver/stackdriver_test.go:556 +0xad5
  testing.tRunner()
      /Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:774 +0x16d
==================
--- FAIL: TestBundlerRace (0.41s)
	testing.go:727: race detected during execution of test
FAIL
exit status 1
FAIL	go.opencensus.io/exporter/stats/stackdriver	0.436s
```

**Comment by rakyll** [comment] 2017-12-14 19:42
Duplicate of https://github.com/census-instrumentation/opencensus-go/issues/206.

**Closed by rakyll** 2017-12-14 19:42 UTC
Labels: stats
